### ISSUE TITLE
.streamlit/config.toml not taken into account

### ISSUE THREAD

**Issue by Phuc-RZH** [Coincoin-Dataduck/us-wildfire-study-streamlit#7]
I tried to customize color theme and added ".streamlit/config.toml" config file.
It was correctly pulled/merged but current App does not take it into account.
Any idea why?

**Comment by Coincoin-Dataduck** [comment]
solved by waiting ¯\_(ツ)_/¯

**Comment by Coincoin-Dataduck** [comment]
solved by waiting ¯\_(ツ)_/¯
